name = "ProtocolBuffers"
uuid = "33b38db7-f37a-4066-8d88-48be842fb53f"
authors = ["Tomáš Drvoštěp <tomas.drvostep@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
EnumX = "1"
TranscodingStreams = "0.9"
julia = "1.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
