name = "ProtoBuf"
uuid = "3349acd9-ac6a-5e09-bcdb-63829b23a429"
keywords = ["protobuf", "protoc"]
license = "MIT"
desc = "Julia protobuf implementation"
authors = ["Tomáš Drvoštěp <tomas.drvostep@gmail.com>"]
version = "1.0.8"

[deps]
BufferedStreams = "e1450e63-4bb3-523b-b2a4-4ffa8c0fd77d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
BufferedStreams = "1.1"
EnumX = "1"
TranscodingStreams = "0.9"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
